// <auto-generated />
using System;
using AutoShipServicePOC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoShipServicePOC.Migrations
{
    [DbContext(typeof(SubscriptionContext))]
    [Migration("20240506235023_InitSqlLiteDB")]
    partial class InitSqlLiteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("AutoShipServicePOC.Models.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SubscriptionID")
                        .HasColumnType("TEXT");

                    b.Property<short>("ChangeApplicationId")
                        .HasColumnName("ChangedApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<short>("CreateApplicationId")
                        .HasColumnName("CreatedApplicationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("DatePlaced")
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("EstimatedShipDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ExternalClientId")
                        .HasColumnName("ExternalClientID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnName("OrderID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("OrderTotal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("OtherSubTotal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("xml");

                    b.Property<string>("SalesTax")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<string>("ShippingAndHandling")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("ShippingTax")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("ShippingZip")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<Guid>("TokenInfoId")
                        .HasColumnName("TokenInfoID")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
